/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projeto.javafx;

import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
        launch(args);
    }
 
    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Esse e o PALCO");
        Button button = new Button();
        button.setText("MUE BOTAO");
        stackPane stackPane new.StackPane();
        primaryStage.setScene(new Scene(stackPane, 800, 600));
        primaryStage.show();
    }
}
